[project]
name = "pytexas-github-io"
version = "0.1.0"
description = "PyTexas Foundation Website"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material-extensions>=1.3.1",
    "mkdocs-material[imaging]>=9.6.14",
    "mkdocs-redirects>=1.2.2",
]
