authors:
  masonegger:
    name: Mason Egger
    description: Developer, Educator, Community Organizer
    avatar: https://github.com/masonegger.png
  jaymiller:
    name: Jay Miller
    description: Developer, Community Builder
    avatar: https://github.com/kjaymiller.png