name: Check Links

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.2.0
        with:
          # Check all markdown, HTML, and other text files
          args: >
            --verbose
            --no-progress
            --accept 200,204,206,301,302,307,308
            "**/*.md"
            "**/*.html"
            "**/*.yml"
            "**/*.yaml"
            "docs/**/*.md"
          fail: true
          
      - name: Upload results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md